Repository epilog-swu/Front, pull requests merged in 2024-07, with the labels that each got.

#51 Feat/#42 복약 체크리스트 수정 및 메인 그래프 수정
  wear/src/main/java/com/epi/epilog/presentation/BloodSugarInputFragment.kt
  wear/src/main/java/com/epi/epilog/presentation/CalendarInitializer.kt
  wear/src/main/java/com/epi/epilog/presentation/ChartInitializer.kt
  wear/src/main/java/com/epi/epilog/presentation/DayViewContainer.kt
  wear/src/main/java/com/epi/epilog/presentation/MainActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/MedicineActivity.kt
  wear/src/main/res/layout/fragment_blood_sugar_input.xml
Labels: feature

#53 Feat/#42 워치 디벨롭
  wear/src/main/java/com/epi/epilog/presentation/MedicineActivity.kt
  wear/src/main/res/layout/activity_medicine.xml
Labels: feature

#56 Feat/#52 복약 체크리스트 알림 및 위도경도 test
  .idea/deploymentTargetDropDown.xml
  wear/src/main/AndroidManifest.xml
  wear/src/main/java/com/epi/epilog/presentation/CalendarInitializer.kt
  wear/src/main/java/com/epi/epilog/presentation/ChartInitializer.kt
  wear/src/main/java/com/epi/epilog/presentation/MainActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/MedicineActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/NotificationReceiver.kt
  wear/src/main/res/layout/activity_main.xml
Labels: feature

#58 [Feat/#57] 메인 레이아웃 중간 PR
  app/build.gradle.kts
  app/src/main/java/com/epi/epilog/MainActivity.kt
  app/src/main/java/com/epi/epilog/calendarFragment.kt
  app/src/main/res/drawable/calendar_day_bg.xml
  app/src/main/res/drawable/calendar_rangeday_bg.xml
  app/src/main/res/drawable/calendar_selectday_bg.xml
  app/src/main/res/drawable/maincalendar_back.xml
  app/src/main/res/drawable/maincalendar_next.xml
  app/src/main/res/drawable/seizure_check_button.xml
  app/src/main/res/drawable/white_button_shape.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/calendar_day_layout.xml
  app/src/main/res/layout/calendar_day_titles_container.xml
  app/src/main/res/layout/calendar_day_titles_text.xml
  app/src/main/res/layout/calendar_month_year.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/main_calendar.xml
Labels: feature

#61 Feat/#54
  wear/src/main/java/com/epi/epilog/FallDetectionService.kt
  wear/src/main/java/com/epi/epilog/presentation/MealActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/MealNotificationReceiver.kt
  wear/src/main/java/com/epi/epilog/presentation/MedicineActivity.kt
Labels: feature

#62 Feat/#57 메인 캘린더 layout 수정
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/epi/epilog/MainActivity.kt
  app/src/main/java/com/epi/epilog/calendarFragment.kt
  app/src/main/res/drawable/bottom_nav_bg.xml
  app/src/main/res/drawable/bottom_nav_selected_calendar.xml
  app/src/main/res/drawable/bottom_nav_selected_meal.xml
  app/src/main/res/drawable/bottom_nav_selected_medicine.xml
  app/src/main/res/drawable/bottom_nav_selected_my.xml
  app/src/main/res/drawable/bottom_selector_calendar.xml
  app/src/main/res/drawable/bottom_selector_my.xml
  app/src/main/res/drawable/dialog_background.xml
  app/src/main/res/drawable/dialog_line.xml
  app/src/main/res/drawable/epi_dialog_btn.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_main_nav.xml
  app/src/main/res/layout/calendar_day_layout.xml
  app/src/main/res/layout/calendar_day_titles_container.xml
  app/src/main/res/layout/calendar_month_year.xml
  app/src/main/res/layout/epi_dialog_custom.xml
  app/src/main/res/layout/main_calendar.xml
  app/src/main/res/menu/menu_bottom_nav.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: feature

#63 Feat/#54
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/epi/epilog/ActivityShowFailDialog.kt
  app/src/main/java/com/epi/epilog/ActivityShowSuccessDialog.kt
  app/src/main/java/com/epi/epilog/DiaryFragmentWeight.kt
  app/src/main/java/com/epi/epilog/DiaryWriteActivity.kt
  app/src/main/java/com/epi/epilog/signUp1Activity.kt
  app/src/main/java/com/epi/epilog/signUp2Activity.kt
  app/src/main/java/com/epi/epilog/signUp3Activity.kt
  app/src/main/java/com/epi/epilog/signUp4Activity.kt
  app/src/main/java/com/epi/epilog/signUp5Activity.kt
  app/src/main/res/layout/activity_diary_write.xml
  app/src/main/res/layout/dialog_fail.xml
  app/src/main/res/layout/dialog_success.xml
  app/src/main/res/layout/diary_edit_1.xml
  app/src/main/res/layout/diary_fragment_mood.xml
  app/src/main/res/layout/diary_fragment_weight.xml
  app/src/main/res/layout/sign_up_1.xml
  app/src/main/res/layout/sign_up_2.xml
  app/src/main/res/layout/sign_up_3.xml
  app/src/main/res/layout/sign_up_4.xml
  app/src/main/res/layout/sign_up_4_detail.xml
  app/src/main/res/layout/sign_up_5.xml
  app/src/main/res/layout/time_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature

#66 Feat/#57 calendarFragment.kt 파일 수정
  app/src/main/java/com/epi/epilog/MainActivity.kt
  app/src/main/java/com/epi/epilog/Main_bsd_nodiary_Fragment.kt
  app/src/main/java/com/epi/epilog/calendarFragment.kt
Labels: feature

#67 feat/#54 : FCM 기기 토큰, 웹 소켓 연결, 복약체크리스트 레이아웃
  .idea/.name
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/epi/epilog/ItemListDialogFragment.kt
  app/src/main/res/drawable/bottom_sheet_background.xml
  app/src/main/res/layout/dialog_bottom_sheet.xml
  app/src/main/res/layout/fragment_week_calendar.xml
  app/src/main/res/layout/medicine_checklist.xml
  app/src/main/res/layout/medicine_dialog.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
  wear/build.gradle.kts
  wear/google-services.json
  wear/src/main/AndroidManifest.xml
  wear/src/main/java/api/RetrofitService.kt
  wear/src/main/java/com/epi/epilog/FallDetectionService.kt
  wear/src/main/java/com/epi/epilog/presentation/LoginActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/MyApplication.kt
  wear/src/main/java/com/epi/epilog/presentation/MyFirebaseMessagingService.kt
  wear/src/main/res/values-round/strings.xml
  wear/src/main/res/values/strings.xml
Labels: feature

#68 Feat/#57 중간커밋
  app/src/main/java/com/epi/epilog/Main_bsd_nodiary_Fragment.kt
  app/src/main/java/com/epi/epilog/Main_bsd_see_seizure_Fragment.kt
  app/src/main/res/layout/fragment_main_bsd_existdiary.xml
Labels: feature

#70 [Feat/#69]
  .idea/deploymentTargetDropDown.xml
  .idea/deploymentTargetSelector.xml
  .idea/other.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/epi/epilog/ActivityMealManageExercise.kt
  app/src/main/java/com/epi/epilog/ActivityMealManageSex.kt
  app/src/main/java/com/epi/epilog/ActivityMealManageWeight.kt
  app/src/main/java/com/epi/epilog/MainActivity.kt
  app/src/main/java/com/epi/epilog/mealChecklistFragment.kt
  app/src/main/res/drawable/app_week_cal_selected_date.png
  app/src/main/res/drawable/bottom_nav_calendar.png
  app/src/main/res/drawable/bottom_nav_calender.xml
  app/src/main/res/drawable/bottom_nav_capsule.png
  app/src/main/res/drawable/bottom_nav_capsule.xml
  app/src/main/res/drawable/bottom_nav_food.png
  app/src/main/res/drawable/bottom_nav_my.png
  app/src/main/res/drawable/bottom_nav_my.xml
  app/src/main/res/drawable/bottom_nav_selected_calendar.xml
  app/src/main/res/drawable/bottom_nav_selected_meal.xml
  app/src/main/res/drawable/bottom_nav_selected_medicine.xml
  app/src/main/res/drawable/bottom_nav_selected_my.xml
  app/src/main/res/drawable/bottom_nav_watch.xml
  app/src/main/res/drawable/bottom_selector_calendar.xml
  app/src/main/res/drawable/bottom_selector_my.xml
  app/src/main/res/drawable/edit_text_background.png
  app/src/main/res/drawable/epi_checklist_check.png
  app/src/main/res/drawable/epi_checklist_checkbtn.xml
  app/src/main/res/drawable/epi_checklist_noncheck.png
  app/src/main/res/drawable/epi_mealchecklist_addmeal.png
  app/src/main/res/drawable/food_basic_image1.png
  app/src/main/res/drawable/food_basic_image2.png
  app/src/main/res/drawable/food_basic_image3.png
  app/src/main/res/drawable/food_basic_image4.png
  app/src/main/res/drawable/meal_detail_basic_image.png
  app/src/main/res/drawable/meal_memo_box.png
  app/src/main/res/drawable/meal_time_box.png
  app/src/main/res/drawable/oneday_energy_bg.png
  app/src/main/res/drawable/register_btn.png
  app/src/main/res/drawable/small_box.png
  app/src/main/res/layout/activity_meal_add.xml
  app/src/main/res/layout/activity_meal_detail.xml
  app/src/main/res/layout/activity_meal_manage_exercise.xml
  app/src/main/res/layout/activity_meal_manage_sex.xml
  app/src/main/res/layout/activity_meal_manage_weight.xml
  app/src/main/res/layout/activity_meal_time.xml
  app/src/main/res/layout/fragment_meal_checklist.xml
  app/src/main/res/layout/meal_add_item.xml
  app/src/main/res/layout/meal_checklist_item.xml
  app/src/main/res/layout/meal_detail_item.xml
  app/src/main/res/layout/week_calendar_day_layout.xml
  app/src/main/res/layout/week_calendar_day_title_text.xml
  app/src/main/res/layout/week_calendar_day_titles_container.xml
  app/src/main/res/menu/menu_bottom_nav.xml
  app/src/main/res/values/strings.xml
Labels: feature

#72 [Feat/#69] : 메인 xml 및 kt 파일 수정(바텀네비게이션 및 액션바 관련, 식사 체크리스트 레이아웃 1-1 제작)
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/epi/epilog/MainActivity.kt
  app/src/main/java/com/epi/epilog/calendarFragment.kt
  app/src/main/java/com/epi/epilog/mealChecklistFragment.kt
  app/src/main/res/drawable/meal_checklist_checkbtn.xml
  app/src/main/res/drawable/meal_checklist_see_meal_btn.png
  app/src/main/res/drawable/meal_pie_graph_box.png
  app/src/main/res/drawable/meal_today_cal_box.png
  app/src/main/res/drawable/meal_today_cal_box_line.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_graph.xml
  app/src/main/res/layout/fragment_meal_checklist.xml
  app/src/main/res/layout/main_calendar.xml
  app/src/main/res/layout/meal_checklist_item.xml
Labels: feature

#73 Feat/#69 메인에서 각종 프래그먼트 연결 및 상단제어바 제어
  app/src/main/java/com/epi/epilog/MainActivity.kt
  app/src/main/java/com/epi/epilog/calendarFragment.kt
  app/src/main/java/com/epi/epilog/unable.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/fragment_graph.xml
  app/src/main/res/layout/fragment_meal_checklist.xml
  app/src/main/res/layout/main_calendar.xml
Labels: feature

#75 feat/#74: 각속도 센서 추가
  wear/src/main/java/api/RetrofitService.kt
  wear/src/main/java/com/epi/epilog/FallDetectionService.kt
Labels: fix, feature

#77 [feat/#74]: 낙상감지 웹소켓 이벤트 핸들링
  wear/src/main/java/com/epi/epilog/FallDetectionService.kt
  wear/src/main/java/com/epi/epilog/presentation/FallDetectionActivity.kt
Labels: fix, feature

#78 [feat/#74]: 낙상감지 비상알림 수정(타이머 추가)
  wear/src/main/java/com/epi/epilog/FallDetectionService.kt
  wear/src/main/java/com/epi/epilog/presentation/FallDetectionActivity.kt
  wear/src/main/res/layout/activity_fall_detection.xml
Labels: fix

#80 fix/#79: 낙상감지 emer 이벤트 연결 및 ux 수정
  .idea/.name
  .idea/deploymentTargetDropDown.xml
  settings.gradle.kts
  wear/build.gradle.kts
  wear/src/main/java/com/epi/epilog/FallDetectionService.kt
  wear/src/main/java/com/epi/epilog/presentation/FallDetectionActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/LoginActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/RetrofitClient.kt
Labels: feature, refactor

#81 Feat/#69
  .idea/deploymentTargetSelector.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/epi/epilog/GraphPage.kt
  app/src/main/java/com/epi/epilog/MainActivity.kt
  app/src/main/java/com/epi/epilog/calendarFragment.kt
  app/src/main/java/com/epi/epilog/graphFragment.kt
  app/src/main/java/com/epi/epilog/meal/ActivityMealManageExercise.kt
  app/src/main/java/com/epi/epilog/meal/ActivityMealManageSex.kt
  app/src/main/java/com/epi/epilog/meal/ActivityMealManageWeight.kt
  app/src/main/java/com/epi/epilog/meal/mealChecklistFragment.kt
  app/src/main/res/drawable/graph_avg_bloodsugar_bg.png
  app/src/main/res/drawable/graph_avg_bloodsugar_meal_bg.png
  app/src/main/res/drawable/graph_marker.xml
  app/src/main/res/drawable/graph_marker_bmi.xml
  app/src/main/res/drawable/graph_marker_tail.xml
  app/src/main/res/drawable/graph_marker_tail_bmi.xml
  app/src/main/res/drawable/graph_marker_weight.xml
  app/src/main/res/drawable/graph_marker_weight_tail.xml
  app/src/main/res/drawable/main_graph_plain_day_bg.xml
  app/src/main/res/drawable/main_graph_selected_day_bg.xml
  app/src/main/res/drawable/main_graph_week_calendar_plain_bg.png
  app/src/main/res/drawable/main_graph_week_calendar_selected_bg.png
  app/src/main/res/layout/fragment_graph.xml
  app/src/main/res/layout/fragment_meal_checklist.xml
  app/src/main/res/layout/graph_marker_bmi_layout.xml
  app/src/main/res/layout/graph_marker_layout.xml
  app/src/main/res/layout/graph_marker_weight_layout.xml
Labels: feature, design

#82 Feat/#54 : 복약체크리스트 코드 수정, 모바일 로그인 시 FCM 전송
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/api/RetrofitService.kt
  app/src/main/java/com/epi/epilog/DeleteDialogFragment.kt
  app/src/main/java/com/epi/epilog/LoginActivity.kt
  app/src/main/java/com/epi/epilog/MedicineAddModifyActivity.kt
  app/src/main/java/com/epi/epilog/MedicineBottomSheetFragment.kt
  app/src/main/java/com/epi/epilog/MedicineBottomSheetFragment2.kt
  app/src/main/java/com/epi/epilog/MedicineChecklistFragment.kt
  app/src/main/java/com/epi/epilog/MedicineDetailActivity.kt
  app/src/main/java/com/epi/epilog/signUp4Activity.kt
  app/src/main/res/drawable/checkbox_thumb_selector.xml
  app/src/main/res/drawable/checkbox_track_selector.xml
  app/src/main/res/drawable/grey_box.xml
  app/src/main/res/layout/fragment_medicine_checklist.xml
  app/src/main/res/layout/fragment_medicine_checklist_item.xml
  app/src/main/res/layout/medicine_add.xml
  app/src/main/res/layout/medicine_add_detail.xml
  app/src/main/res/layout/medicine_item.xml
  app/src/main/res/layout/medicine_list_item.xml
  app/src/main/res/layout/medicine_list_item_detail.xml
  app/src/main/res/layout/sign_up_4.xml
  app/src/main/res/layout/sign_up_4_detail.xml
Labels: feature

#84 feat/#93: 소켓 엔드포인트 수정
  wear/src/main/java/com/epi/epilog/FallDetectionService.kt
Labels: fix
