Repository epilog-swu/Front, pull requests merged in 2024-08, with the labels that each got.

#88 [Feat/#83] 메인 그래프 수정 및 api 연동
  .idea/.name
  .idea/deploymentTargetSelector.xml
  .idea/other.xml
  app/src/main/java/com/epi/epilog/BottomSheetFragment.kt
  app/src/main/java/com/epi/epilog/GraphPage.kt
  app/src/main/java/com/epi/epilog/LoginActivity.kt
  app/src/main/java/com/epi/epilog/MedicineAddModifyActivity.kt
  app/src/main/java/com/epi/epilog/MedicineChecklistFragment.kt
  app/src/main/java/com/epi/epilog/api/RetrofitService.kt
  app/src/main/java/com/epi/epilog/calendarFragment.kt
  app/src/main/java/com/epi/epilog/signUp1Activity.kt
  app/src/main/java/com/epi/epilog/signUp4Activity.kt
  app/src/main/java/com/epi/epilog/signUp5Activity.kt
  app/src/main/java/com/epi/epilog/startActivity.kt
  app/src/main/res/layout/fragment_graph.xml
Labels: feature

#89 [Feat/#87] 일지등록 api 연결 성공
  app/src/main/java/com/epi/epilog/ActivityShowSuccessDialog.kt
  app/src/main/java/com/epi/epilog/BottomSheetFragment.kt
  app/src/main/java/com/epi/epilog/DiaryEditActivity.kt
  app/src/main/java/com/epi/epilog/DiaryFragmentBloodPressure.kt
  app/src/main/java/com/epi/epilog/DiaryFragmentBloodSugar.kt
  app/src/main/java/com/epi/epilog/DiaryFragmentExercise.kt
  app/src/main/java/com/epi/epilog/DiaryFragmentMood.kt
  app/src/main/java/com/epi/epilog/DiaryFragmentWeight.kt
  app/src/main/java/com/epi/epilog/DiaryWriteActivity.kt
  app/src/main/java/com/epi/epilog/MainActivity.kt
  app/src/main/java/com/epi/epilog/api/DiaryFragment.kt
  app/src/main/java/com/epi/epilog/api/RetrofitService.kt
  app/src/main/java/com/epi/epilog/calendarFragment.kt
  app/src/main/res/drawable/calendar_today_bg.xml
  app/src/main/res/layout/diary_fragment_mood.xml
Labels: fix, feature, chore

#90 Feat/#85 : 디자인 디테일 수정, 워치/모바일 권한 및 토큰 유효성 검사
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/epi/epilog/LoginActivity.kt
  app/src/main/java/com/epi/epilog/MainActivity.kt
  app/src/main/java/com/epi/epilog/MedicineChecklistFragment.kt
  app/src/main/java/com/epi/epilog/MyPageFragment.kt
  app/src/main/java/com/epi/epilog/api/RetrofitService.kt
  app/src/main/java/com/epi/epilog/startActivity.kt
  app/src/main/res/drawable/bottom_stroke_light_purple.xml
  app/src/main/res/drawable/light_purple_shape.xml
  app/src/main/res/drawable/red_badge.xml
  app/src/main/res/layout/fragment_medicine_checklist.xml
  app/src/main/res/layout/fragment_medicine_checklist_header.xml
  app/src/main/res/layout/fragment_medicine_checklist_item.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/meal_checklist_item.xml
  app/src/main/res/layout/medicine_detail.xml
  wear/src/main/AndroidManifest.xml
  wear/src/main/java/api/RetrofitService.kt
  wear/src/main/java/com/epi/epilog/presentation/LoginActivity.kt
Labels: feature

#91 [Feat/#83] PR위한 중간 커밋
  .idea/deploymentTargetSelector.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/epi/epilog/startActivity.kt
Labels: feature, chore, merge

#94 [Feat/#92] 월별 일지 개수 조회 api 연동 및 UI 변경
  app/src/main/java/com/epi/epilog/CalendarPage.kt
  app/src/main/java/com/epi/epilog/api/RetrofitService.kt
  app/src/main/java/com/epi/epilog/calendarFragment.kt
  app/src/main/res/drawable/calendar_day_count1_bg.xml
  app/src/main/res/drawable/calendar_day_count3_bg.xml
Labels: feature, design, chore

#95 [Feat/#92] 메인 캘린더 일지 조회 api 연결 완료
  app/src/main/java/com/epi/epilog/BottomSheetFragment.kt
  app/src/main/java/com/epi/epilog/CalendarPage.kt
  app/src/main/java/com/epi/epilog/Main_bsd_see_seizure_Fragment.kt
  app/src/main/java/com/epi/epilog/Main_bsd_select_seizure_Fragment.kt
  app/src/main/java/com/epi/epilog/api/RetrofitService.kt
  app/src/main/res/drawable/dialog_diarybsd_bg.png
  app/src/main/res/drawable/icon_blood_pressure.png
  app/src/main/res/drawable/icon_blood_sugar.png
  app/src/main/res/drawable/icon_cloud.png
  app/src/main/res/drawable/icon_exercise.png
  app/src/main/res/drawable/icon_mood.png
  app/src/main/res/drawable/icon_moon.png
  app/src/main/res/drawable/icon_sun.png
  app/src/main/res/drawable/icon_weight.png
  app/src/main/res/layout/fragment_bsd_nodiary.xml
  app/src/main/res/layout/fragment_bsd_yes_diary.xml
  app/src/main/res/layout/fragment_main_bsd_existdiary.xml
  app/src/main/res/layout/fragment_main_bsd_select_seizure_.xml
  app/src/main/res/layout/fragment_medicine_select_bottom_2.xml
Labels: feature, design

#96 [Feat/#92] 식사 체크리스트 레이아웃 수정 및 GraphPage x,y축 설정 변경
  app/src/main/java/com/epi/epilog/GraphPage.kt
  app/src/main/res/layout/fragment_meal_checklist.xml
Labels: feature, design, chore

#101 [Feat/#93] : 시작페이지 스플래시 추가, 복약 상세조회 API 연동, 복약체크리스트 색상 및 코드 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/epi/epilog/CalendarPage.kt
  app/src/main/java/com/epi/epilog/DeleteDialogFragment.kt
  app/src/main/java/com/epi/epilog/api/RetrofitService.kt
  app/src/main/java/com/epi/epilog/meal/mealChecklistFragment.kt
  app/src/main/java/com/epi/epilog/medicine/ActivityMedicineDetail.kt
  app/src/main/java/com/epi/epilog/medicine/DeleteDialogFragment.kt
  app/src/main/java/com/epi/epilog/medicine/MedicineBottomSheetFragment.kt
  app/src/main/java/com/epi/epilog/medicine/MedicineChecklistFragment.kt
  app/src/main/java/com/epi/epilog/medicine/MedicineDetailActivity.kt
  app/src/main/java/com/epi/epilog/startActivity.kt
  app/src/main/res/anim/slide_in.xml
  app/src/main/res/drawable/gradient_background.xml
  app/src/main/res/drawable/gradient_drawable.xml
  app/src/main/res/drawable/light_purple_shape.xml
  app/src/main/res/drawable/logoo.xml
  app/src/main/res/drawable/start_oval.xml
  app/src/main/res/layout/activity_start.xml
  app/src/main/res/layout/medicine_detail.xml
  wear/src/main/res/values/colors.xml
Labels: fix, feature, design

#102 feat/#93 : FCM json 파일 및 코드 수정, 패키지 분류
  .idea/deploymentTargetDropDown.xml
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/epi/epilog/LoginActivity.kt
  app/src/main/java/com/epi/epilog/MainActivity.kt
  app/src/main/java/com/epi/epilog/diary/ActivityDiaryShowDetail.kt
  app/src/main/java/com/epi/epilog/diary/ActivityShowFailDialog.kt
  app/src/main/java/com/epi/epilog/diary/ActivityShowSuccessDialog.kt
  app/src/main/java/com/epi/epilog/diary/DiaryWriteActivity.kt
  app/src/main/java/com/epi/epilog/main/BottomSheetFragment.kt
  app/src/main/java/com/epi/epilog/main/CalendarAdapter.kt
  app/src/main/java/com/epi/epilog/main/CalendarPage.kt
  app/src/main/java/com/epi/epilog/main/CalendarVO.kt
  app/src/main/java/com/epi/epilog/main/GraphPage.kt
  app/src/main/java/com/epi/epilog/main/calendarFragment.kt
  app/src/main/java/com/epi/epilog/startActivity.kt
  wear/build.gradle.kts
  wear/google-services.json
  wear/src/main/AndroidManifest.xml
  wear/src/main/java/api/RetrofitService.kt
  wear/src/main/java/com/epi/epilog/presentation/LoginActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/MainActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/MyApplication.kt
  wear/src/main/java/com/epi/epilog/presentation/RetrofitClient.kt
  wear/src/main/java/com/epi/epilog/presentation/UpdateChecklistStatusRequest.kt
  wear/src/main/java/com/epi/epilog/presentation/ValidationResponse.kt
  wear/src/main/java/com/epi/epilog/presentation/blood/Blood.kt
  wear/src/main/java/com/epi/epilog/presentation/blood/BloodSugarActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/blood/BloodSugarDatas.kt
  wear/src/main/java/com/epi/epilog/presentation/blood/BloodSugarInputFragment.kt
  wear/src/main/java/com/epi/epilog/presentation/blood/BloodSugarTimeInputFragment.kt
  wear/src/main/java/com/epi/epilog/presentation/calendar/CalendarInitializer.kt
  wear/src/main/java/com/epi/epilog/presentation/calendar/ChartInitializer.kt
  wear/src/main/java/com/epi/epilog/presentation/calendar/DayViewContainer.kt
  wear/src/main/java/com/epi/epilog/presentation/fall/BootBroadcastReceiver.kt
  wear/src/main/java/com/epi/epilog/presentation/fall/FallDetectionActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/fall/FallDetectionService.kt
  wear/src/main/java/com/epi/epilog/presentation/fall/MyFirebaseMessagingService.kt
  wear/src/main/java/com/epi/epilog/presentation/fall/SoundRecognizerActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/meal/MealActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/meal/MealNotificationReceiver.kt
  wear/src/main/java/com/epi/epilog/presentation/medicine/MedicineActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/medicine/MedicineCheckListDatas.kt
  wear/src/main/java/com/epi/epilog/presentation/medicine/MedicineNotificationReceiver.kt
Labels: fix, feature

#103 feat/#93 : FCM 기기 토큰토큰 전송 코드 TODO로 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/epi/epilog/LoginActivity.kt
  wear/build.gradle.kts
  wear/google-services.json
  wear/src/main/AndroidManifest.xml
  wear/src/main/java/com/epi/epilog/presentation/LoginActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/MainActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/blood/BloodSugarActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/blood/BloodSugarInputFragment.kt
  wear/src/main/java/com/epi/epilog/presentation/blood/BloodSugarTimeInputFragment.kt
  wear/src/main/java/com/epi/epilog/presentation/calendar/CalendarInitializer.kt
  wear/src/main/java/com/epi/epilog/presentation/calendar/DayViewContainer.kt
  wear/src/main/java/com/epi/epilog/presentation/fall/FallDetectionActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/fall/FallDetectionService.kt
  wear/src/main/java/com/epi/epilog/presentation/fall/SoundRecognizerActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/meal/MealActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/meal/MealNotificationReceiver.kt
  wear/src/main/java/com/epi/epilog/presentation/medicine/MedicineActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/medicine/MedicineNotificationReceiver.kt
  wear/src/main/res/layout/login.xml
Labels: fix

#104 [Feat/#92] 일지 상세 조회, 등록 및 세부 수정사항 수정
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/epi/epilog/diary/ActivityDiaryShowDetail.kt
  app/src/main/java/com/epi/epilog/diary/DiaryFragmentBloodPressure.kt
  app/src/main/java/com/epi/epilog/diary/DiaryWriteActivity.kt
  app/src/main/java/com/epi/epilog/main/BottomSheetFragment.kt
  app/src/main/java/com/epi/epilog/medicine/MedicineChecklistFragment.kt
  app/src/main/res/drawable/icon_falldown.png
  app/src/main/res/layout/activity_diary_show_detail.xml
  app/src/main/res/layout/diary_fragment_blood_pressure.xml
  app/src/main/res/layout/diary_fragment_blood_sugar.xml
  app/src/main/res/layout/diary_fragment_exercise.xml
  app/src/main/res/layout/diary_fragment_mood.xml
  app/src/main/res/layout/diary_fragment_weight.xml
  app/src/main/res/layout/fragment_bsd_yes_diary.xml
  app/src/main/res/layout/yes_diary_count_layout.xml
  wear/src/main/res/layout/activity_checklist_dialog_2.xml
Labels: feature, design

#105 Feat/#93 : 복약체크리스트 코드 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/epi/epilog/medicine/MedicineBottomSheetFragment.kt
  app/src/main/java/com/epi/epilog/medicine/MedicineChecklistFragment.kt
  app/src/main/java/com/epi/epilog/startActivity.kt
Labels: feature

#106 [Feat/#92] 일지 작성 프래그먼트 초기화 문제 해결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/epi/epilog/api/RetrofitService.kt
  app/src/main/java/com/epi/epilog/diary/DiaryShowDetailActivity.kt
  app/src/main/java/com/epi/epilog/diary/DiaryWriteActivity.kt
  app/src/main/java/com/epi/epilog/main/BottomSheetFragment.kt
  app/src/main/java/com/epi/epilog/main/CalendarAdapter.kt
  app/src/main/java/com/epi/epilog/main/CalendarFragment.kt
  app/src/main/java/com/epi/epilog/main/CalendarVO.kt
Labels: fix

#107 [Feat/#93] : 시작화면 스플래시& 앱 이름에 폰트 적용, 복약체크리스트 수정 API 연동
  app/src/main/java/com/epi/epilog/api/MedicationStatusUpdateRequest.kt
  app/src/main/java/com/epi/epilog/api/RetrofitService.kt
  app/src/main/java/com/epi/epilog/main/CalendarPage.kt
  app/src/main/java/com/epi/epilog/meal/mealChecklistFragment.kt
  app/src/main/java/com/epi/epilog/medicine/MedicineBottomSheetFragment.kt
  app/src/main/java/com/epi/epilog/medicine/MedicineBottomSheetFragment2.kt
  app/src/main/java/com/epi/epilog/medicine/MedicineChecklistFragment.kt
  app/src/main/java/com/epi/epilog/startActivity.kt
  app/src/main/res/font/montserrat.ttf
  app/src/main/res/font/montserrat_bold.ttf
  app/src/main/res/font/montserrat_light.ttf
  app/src/main/res/font/montserrat_regular.ttf
  app/src/main/res/font/montserrat_semi.ttf
  app/src/main/res/font/montserrat_thin.ttf
  app/src/main/res/layout/activity_start.xml
  app/src/main/res/layout/fragment_meal_checklist.xml
  app/src/main/res/layout/fragment_medicine_checklist.xml
Labels: feature

#108 [Feat/#92] 일지 상세 조회 UI comment로 받을 수 있도록 수정
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/epi/epilog/diary/DiaryShowDetailActivity.kt
Labels: fix, feature, chore

#109 [Feat/#92] 워치 버그 수정
  .idea/deploymentTargetSelector.xml
  .idea/other.xml
  wear/src/main/java/com/epi/epilog/presentation/MainActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/calendar/CalendarInitializer.kt
Labels: fix, feature, refactor, chore

#110 [Feat/#92] 메인 그래프, 캘린더 세부수정
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/epi/epilog/LoginActivity.kt
  app/src/main/java/com/epi/epilog/main/CalendarPage.kt
  app/src/main/java/com/epi/epilog/main/GraphPage.kt
  app/src/main/res/layout/fragment_graph.xml
Labels: fix, feature, refactor, chore

#111 Feat/#93 : 복약체크리스트 수정 API 연동
  app/src/main/java/com/epi/epilog/medicine/MedicineAdapter.kt
  app/src/main/java/com/epi/epilog/medicine/MedicineBottomSheetFragment.kt
  app/src/main/java/com/epi/epilog/medicine/MedicineChecklistFragment.kt
  app/src/main/java/com/epi/epilog/signup/SignUp5Activity.kt
  app/src/main/java/com/epi/epilog/startActivity.kt
  app/src/main/res/layout/activity_start.xml
  app/src/main/res/layout/fragment_medicine_checklist.xml
  app/src/main/res/layout/medicine_checklist_dialog.xml
Labels: feature

#112 [Feat/#92] 팩토리 구분 및 워치 식사, 복약 취소시 토스트 메시지 띄우기
  .idea/deploymentTargetSelector.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/epi/epilog/api/ApiResponse.kt
  app/src/main/java/com/epi/epilog/api/RetrofitService.kt
  app/src/main/java/com/epi/epilog/diary/DiaryWriteActivity.kt
  app/src/main/java/com/epi/epilog/main/CalendarPage.kt
  app/src/main/java/com/epi/epilog/main/MainActivity.kt
  app/src/main/java/com/epi/epilog/medicine/DeleteDialogFragment.kt
  app/src/main/java/com/epi/epilog/medicine/MedicineAddModifyActivity.kt
  app/src/main/java/com/epi/epilog/medicine/MedicineChecklistFragment.kt
  app/src/main/java/com/epi/epilog/medicine/MedicineDetailActivity.kt
  app/src/main/java/com/epi/epilog/my/MyPageFragment.kt
  app/src/main/java/com/epi/epilog/signup/LoginActivity.kt
  app/src/main/java/com/epi/epilog/signup/SignUp1Activity.kt
  app/src/main/java/com/epi/epilog/signup/SignUp5Activity.kt
  app/src/main/java/com/epi/epilog/signup/StartActivity.kt
  app/src/main/java/com/epi/epilog/unable.kt
  app/src/main/res/layout/activity_app_guide_swipe.xml
  wear/src/main/AndroidManifest.xml
  wear/src/main/java/api/ApiResponse.kt
  wear/src/main/java/api/RetrofitService.kt
  wear/src/main/java/com/epi/epilog/presentation/LoginActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/blood/BloodSugarInputFragment.kt
  wear/src/main/java/com/epi/epilog/presentation/fall/FallDetectionActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/main/CalendarInitializer.kt
  wear/src/main/java/com/epi/epilog/presentation/main/ChartInitializer.kt
  wear/src/main/java/com/epi/epilog/presentation/main/DayViewContainer.kt
  wear/src/main/java/com/epi/epilog/presentation/main/MainActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/meal/MealActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/medicine/MedicineActivity.kt
Labels: fix, feature, chore

#114 [Feat/#92] 깃충돌해결 : 워치 토스트 메시지 수정
  wear/src/main/java/com/epi/epilog/presentation/meal/MealActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/medicine/MedicineActivity.kt
Labels: fix, merge

#116 [Feat/#92] diaryfragmentmood.xml 및 kt 파일 수정(선택 항목 더 많게), 일지 상세 조회 뱃지 로직 수정
  app/src/main/java/com/epi/epilog/diary/DiaryFragmentMood.kt
  app/src/main/java/com/epi/epilog/diary/DiaryShowDetailActivity.kt
  app/src/main/res/layout/diary_fragment_mood.xml
Labels: feature, design, chore

#117 [Feat/#92] UI 세부수정(일지 작성 및 메인바텀시트)
  .idea/deploymentTargetSelector.xml
  .idea/other.xml
  app/src/main/res/layout/diary_fragment_weight.xml
  app/src/main/res/layout/fragment_bsd_nodiary.xml
  app/src/main/res/layout/fragment_bsd_yes_diary.xml
Labels: chore

#119 [Feat/#92] 세부수정 및 깃충돌해결
  .idea/deploymentTargetSelector.xml
  wear/src/main/java/com/epi/epilog/presentation/blood/BloodSugarInputFragment.kt
  wear/src/main/res/layout/activity_blood_sugar.xml
Labels: fix, feature, chore

#120 [Feat/#92] wear 코드 리팩토링 1차
  .idea/deploymentTargetSelector.xml
  wear/src/main/java/com/epi/epilog/presentation/blood/BloodSugarActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/blood/BloodSugarInputFragment.kt
  wear/src/main/java/com/epi/epilog/presentation/blood/BloodSugarTimeInputFragment.kt
  wear/src/main/java/com/epi/epilog/presentation/fall/BootBroadcastReceiver.kt
  wear/src/main/java/com/epi/epilog/presentation/fall/FallDetectionService.kt
  wear/src/main/java/com/epi/epilog/presentation/meal/MealActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/medicine/MedicineActivity.kt
  wear/src/main/res/layout/activity_blood_sugar.xml
  wear/src/main/res/layout/activity_checklist_dialog.xml
  wear/src/main/res/layout/activity_checklist_dialog_meal.xml
  wear/src/main/res/layout/activity_checklist_dialog_medicine.xml
  wear/src/main/res/layout/activity_fall_detection.xml
  wear/src/main/res/layout/activity_main.xml
  wear/src/main/res/layout/activity_medicine.xml
  wear/src/main/res/layout/calendar_day_titles_container.xml
  wear/src/main/res/layout/checkbox_item.xml
  wear/src/main/res/layout/fragment_blood_sugar_input.xml
  wear/src/main/res/layout/fragment_blood_sugar_time_input.xml
  wear/src/main/res/layout/login.xml
  wear/src/main/res/layout/login_modal.xml
Labels: refactor, chore
