Repository epilog-swu/Front, pull requests merged in 2024-05, with the labels that each got.

#22 [build] wear os 모듈 추가
  .idea/gradle.xml
  gradle/libs.versions.toml
  settings.gradle.kts
  wear/.gitignore
  wear/build.gradle.kts
  wear/lint.xml
  wear/proguard-rules.pro
  wear/src/main/AndroidManifest.xml
  wear/src/main/java/com/epi/epilog/presentation/MainActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/theme/Theme.kt
  wear/src/main/res/drawable/splash_icon.xml
  wear/src/main/res/mipmap-hdpi/ic_launcher.webp
  wear/src/main/res/mipmap-mdpi/ic_launcher.webp
  wear/src/main/res/mipmap-xhdpi/ic_launcher.webp
  wear/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  wear/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  wear/src/main/res/values-round/strings.xml
  wear/src/main/res/values/strings.xml
  wear/src/main/res/values/styles.xml
Labels: feature

#24 [Feat] 워치 체크리스트 초기 형태 추가
  .idea/deploymentTargetDropDown.xml
  gradle/libs.versions.toml
  wear/build.gradle.kts
  wear/src/main/AndroidManifest.xml
  wear/src/main/java/com/epi/epilog/presentation/MainActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/MedicineActivity.kt
  wear/src/main/res/drawable/check.png
  wear/src/main/res/drawable/checkbox_back.xml
  wear/src/main/res/drawable/checkbox_false.png
  wear/src/main/res/drawable/checkbox_true.png
  wear/src/main/res/drawable/checklist_dialog_btn.xml
  wear/src/main/res/drawable/checklist_item.xml
  wear/src/main/res/layout/activity_checklist_dialog.xml
  wear/src/main/res/layout/activity_medicine.xml
  wear/src/main/res/layout/checkbox_item.xml
  wear/src/main/res/values/colors.xml
  wear/src/main/res/values/strings.xml
Labels: feature, design

#28 Feat/#27 워치 그래프 UI 수정 및 액티비티 연결
  .idea/deploymentTargetDropDown.xml
  wear/build.gradle.kts
  wear/src/main/AndroidManifest.xml
  wear/src/main/java/com/epi/epilog/presentation/MainActivity.kt
  wear/src/main/res/drawable/round_background.xml
  wear/src/main/res/layout/activity_main.xml
  wear/src/main/res/values/styles.xml
Labels: feature, design

#33 [Feat/#27] 캘린더 및 그래프 구현
  wear/src/main/AndroidManifest.xml
  wear/src/main/java/com/epi/epilog/presentation/BloodSugarActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/CalendarInitializer.kt
  wear/src/main/java/com/epi/epilog/presentation/ChartInitializer.kt
  wear/src/main/java/com/epi/epilog/presentation/DayViewContainer.kt
  wear/src/main/java/com/epi/epilog/presentation/MainActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/MealActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/MedicineActivity.kt
  wear/src/main/res/drawable/selected_date.xml
  wear/src/main/res/layout/activity_graph.xml
  wear/src/main/res/layout/activity_main.xml
  wear/src/main/res/layout/calendar_day_layout.xml
  wear/src/main/res/layout/calendar_day_title_text.xml
  wear/src/main/res/layout/calendar_day_titles_container.xml
Labels: feature, design

#38 Chore/#37 : 메인 버튼 텍스트 통일 및 혈당기록 occurrenceType 날짜 + 시간으로 수정
  .idea/deploymentTargetDropDown.xml
  wear/src/main/java/com/epi/epilog/presentation/BloodSugarActivity.kt
  wear/src/main/java/com/epi/epilog/presentation/BloodSugarTimeInputFragment.kt
  wear/src/main/java/com/epi/epilog/presentation/CalendarInitializer.kt
  wear/src/main/java/com/epi/epilog/presentation/MainActivity.kt
  wear/src/main/res/layout/activity_main.xml
Labels: feature, design, chore
