Repository epilog-swu/Front, pull requests merged in 2024-11, with the labels that each got.

#122 [Feat/#92] 메인 캘린더 API 연동 및 기타버그 수정, 2학기 시작전 깃 상태 동기화
  .idea/deploymentTargetSelector.xml
  .idea/other.xml
Labels: feature, refactor, chore, merge

#126 [Fix/#124] 바텀시트 통한 즉각 UI 갱신 성공
  app/src/main/java/com/epi/epilog/medicine/MedicineBottomSheetFragment.kt
  app/src/main/java/com/epi/epilog/medicine/MedicineBottomSheetFragment2.kt
Labels: fix

#127 Feat/#93 : 로그인, PDF, 복약 토큰 유효성 검사 코드 추가
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/epi/epilog/main/CalendarPage.kt
  app/src/main/java/com/epi/epilog/main/GraphPage.kt
  app/src/main/java/com/epi/epilog/medicine/MedicineAddModifyActivity.kt
  app/src/main/java/com/epi/epilog/medicine/MedicineBottomSheetFragment.kt
  app/src/main/java/com/epi/epilog/medicine/MedicineChecklistFragment.kt
  app/src/main/java/com/epi/epilog/signup/LoginActivity.kt
Labels: fix

#129 [Fix/#124] 캘린더 바텀시트 아이콘 패치(몸무게) 해결
  app/src/main/java/com/epi/epilog/diary/DiaryFragmentWeight.kt
  app/src/main/java/com/epi/epilog/diary/DiaryWriteActivity.kt
Labels: fix

#131 [Feat/#130] 식사 체크리스트 레이아웃 제작 완료
  .idea/other.xml
  app/src/main/res/layout/fragment_meal_checklist.xml
  app/src/main/res/layout/fragment_meal_checklist_item.xml
  app/src/main/res/layout/fragment_meal_select_bottom.xml
  app/src/main/res/layout/fragment_meal_select_bottom2.xml
  app/src/main/res/layout/fragment_medicine_checklist.xml
  app/src/main/res/layout/manage_meal_time.xml
  app/src/main/res/layout/manage_meal_time2.xml
  app/src/main/res/layout/meal_add_item.xml
  app/src/main/res/layout/meal_checklist_item.xml
  app/src/main/res/layout/meal_detail_item.xml
  app/src/main/res/layout/meal_time_add_item.xml
Labels: feature, design, merge

#133 [Feat/#132] 식사 체크리스트 조회 및 수정 api 연동
  app/src/main/java/com/epi/epilog/api/MealState.kt
  app/src/main/java/com/epi/epilog/api/RetrofitService.kt
  app/src/main/java/com/epi/epilog/meal/MealBottomSheefFragment.kt
  app/src/main/java/com/epi/epilog/meal/MealBottomSheetFragment2.kt
  app/src/main/java/com/epi/epilog/meal/MealChecklistFragment.kt
  app/src/main/java/com/epi/epilog/meal/mealChecklistFragment.kt
  app/src/main/res/layout/fragment_meal_checklist_item.xml
Labels: feature

#134 [Feat/#132] 식사 시간 조회 및 추가 api 연결 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/epi/epilog/api/NullOnEmptyConverterFactory.kt
  app/src/main/java/com/epi/epilog/api/RetrofitService.kt
  app/src/main/java/com/epi/epilog/meal/MealChecklistFragment.kt
  app/src/main/java/com/epi/epilog/meal/MealManageTime2Activity.kt
  app/src/main/java/com/epi/epilog/meal/MealManageTimeActivity.kt
  app/src/main/res/layout/fragment_meal_checklist_item.xml
  app/src/main/res/layout/manage_meal_time2.xml
  app/src/main/res/layout/meal_time_add_item.xml
Labels: feature
